/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatoRouteRouteImport } from './routes/candidato/route'
import { Route as PanelRouteRouteImport } from './routes/panel/route'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as CCodigoRouteImport } from './routes/c/$codigo'
import { Route as CandidatoIndexRouteImport } from './routes/candidato/index'
import { Route as CastingSlugRouteImport } from './routes/casting/$slug'
import { Route as DossierSlugRouteImport } from './routes/dossier/$slug'
import { Route as PanelIndexRouteImport } from './routes/panel/index'
import { Route as PanelAccesosInvitadosRouteImport } from './routes/panel/accesos-invitados'
import { Route as PanelAdministracionRouteImport } from './routes/panel/administracion'
import { Route as PanelCaptacionRouteImport } from './routes/panel/captacion'
import { Route as PanelClientesRouteImport } from './routes/panel/clientes'
import { Route as PanelDashboardRouteImport } from './routes/panel/dashboard'
import { Route as PanelPortalClienteRouteImport } from './routes/panel/portal-cliente'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalCandidatosRouteImport } from './routes/portal/candidatos'
import { Route as PortalDossiersRouteImport } from './routes/portal/dossiers'
import { Route as PortalSolicitarRouteImport } from './routes/portal/solicitar'
import { Route as PanelCandidatosIndexRouteImport } from './routes/panel/candidatos/index'
import { Route as PanelCandidatosIdRouteImport } from './routes/panel/candidatos/$id'
import { Route as PanelCandidatosImportarRouteImport } from './routes/panel/candidatos/importar'
import { Route as PanelProyectosIndexRouteImport } from './routes/panel/proyectos/index'
import { Route as PanelProyectosIdRouteImport } from './routes/panel/proyectos/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRouteRoute = CandidatoRouteRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRouteRoute = PanelRouteRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodigoRoute = CCodigoRouteImport.update({
  id: '/c/$codigo',
  path: '/c/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoIndexRoute = CandidatoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidatoRouteRoute,
} as any)
const CastingSlugRoute = CastingSlugRouteImport.update({
  id: '/casting/$slug',
  path: '/casting/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierSlugRoute = DossierSlugRouteImport.update({
  id: '/dossier/$slug',
  path: '/dossier/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelAccesosInvitadosRoute = PanelAccesosInvitadosRouteImport.update({
  id: '/accesos-invitados',
  path: '/accesos-invitados',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelAdministracionRoute = PanelAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelCaptacionRoute = PanelCaptacionRouteImport.update({
  id: '/captacion',
  path: '/captacion',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelClientesRoute = PanelClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelDashboardRoute = PanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelPortalClienteRoute = PanelPortalClienteRouteImport.update({
  id: '/portal-cliente',
  path: '/portal-cliente',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalCandidatosRoute = PortalCandidatosRouteImport.update({
  id: '/candidatos',
  path: '/candidatos',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalDossiersRoute = PortalDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalSolicitarRoute = PortalSolicitarRouteImport.update({
  id: '/solicitar',
  path: '/solicitar',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PanelCandidatosIndexRoute = PanelCandidatosIndexRouteImport.update({
  id: '/candidatos/',
  path: '/candidatos/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelCandidatosIdRoute = PanelCandidatosIdRouteImport.update({
  id: '/candidatos/$id',
  path: '/candidatos/$id',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelCandidatosImportarRoute = PanelCandidatosImportarRouteImport.update({
  id: '/candidatos/importar',
  path: '/candidatos/importar',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelProyectosIndexRoute = PanelProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => PanelRouteRoute,
} as any)
const PanelProyectosIdRoute = PanelProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => PanelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidato': typeof CandidatoRouteRouteWithChildren
  '/panel': typeof PanelRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/registro': typeof RegistroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$codigo': typeof CCodigoRoute
  '/casting/$slug': typeof CastingSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/panel/accesos-invitados': typeof PanelAccesosInvitadosRoute
  '/panel/administracion': typeof PanelAdministracionRoute
  '/panel/captacion': typeof PanelCaptacionRoute
  '/panel/clientes': typeof PanelClientesRoute
  '/panel/dashboard': typeof PanelDashboardRoute
  '/panel/portal-cliente': typeof PanelPortalClienteRoute
  '/portal/candidatos': typeof PortalCandidatosRoute
  '/portal/dossiers': typeof PortalDossiersRoute
  '/portal/solicitar': typeof PortalSolicitarRoute
  '/auth/': typeof AuthIndexRoute
  '/candidato/': typeof CandidatoIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/panel/candidatos/$id': typeof PanelCandidatosIdRoute
  '/panel/candidatos/importar': typeof PanelCandidatosImportarRoute
  '/panel/proyectos/$id': typeof PanelProyectosIdRoute
  '/panel/candidatos/': typeof PanelCandidatosIndexRoute
  '/panel/proyectos/': typeof PanelProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registro': typeof RegistroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$codigo': typeof CCodigoRoute
  '/casting/$slug': typeof CastingSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/panel/accesos-invitados': typeof PanelAccesosInvitadosRoute
  '/panel/administracion': typeof PanelAdministracionRoute
  '/panel/captacion': typeof PanelCaptacionRoute
  '/panel/clientes': typeof PanelClientesRoute
  '/panel/dashboard': typeof PanelDashboardRoute
  '/panel/portal-cliente': typeof PanelPortalClienteRoute
  '/portal/candidatos': typeof PortalCandidatosRoute
  '/portal/dossiers': typeof PortalDossiersRoute
  '/portal/solicitar': typeof PortalSolicitarRoute
  '/auth': typeof AuthIndexRoute
  '/candidato': typeof CandidatoIndexRoute
  '/panel': typeof PanelIndexRoute
  '/portal': typeof PortalIndexRoute
  '/panel/candidatos/$id': typeof PanelCandidatosIdRoute
  '/panel/candidatos/importar': typeof PanelCandidatosImportarRoute
  '/panel/proyectos/$id': typeof PanelProyectosIdRoute
  '/panel/candidatos': typeof PanelCandidatosIndexRoute
  '/panel/proyectos': typeof PanelProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidato': typeof CandidatoRouteRouteWithChildren
  '/panel': typeof PanelRouteRouteWithChildren
  '/portal': typeof PortalRouteRouteWithChildren
  '/registro': typeof RegistroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/c/$codigo': typeof CCodigoRoute
  '/casting/$slug': typeof CastingSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/panel/accesos-invitados': typeof PanelAccesosInvitadosRoute
  '/panel/administracion': typeof PanelAdministracionRoute
  '/panel/captacion': typeof PanelCaptacionRoute
  '/panel/clientes': typeof PanelClientesRoute
  '/panel/dashboard': typeof PanelDashboardRoute
  '/panel/portal-cliente': typeof PanelPortalClienteRoute
  '/portal/candidatos': typeof PortalCandidatosRoute
  '/portal/dossiers': typeof PortalDossiersRoute
  '/portal/solicitar': typeof PortalSolicitarRoute
  '/auth/': typeof AuthIndexRoute
  '/candidato/': typeof CandidatoIndexRoute
  '/panel/': typeof PanelIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/panel/candidatos/$id': typeof PanelCandidatosIdRoute
  '/panel/candidatos/importar': typeof PanelCandidatosImportarRoute
  '/panel/proyectos/$id': typeof PanelProyectosIdRoute
  '/panel/candidatos/': typeof PanelCandidatosIndexRoute
  '/panel/proyectos/': typeof PanelProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidato'
    | '/panel'
    | '/portal'
    | '/registro'
    | '/auth/callback'
    | '/c/$codigo'
    | '/casting/$slug'
    | '/dossier/$slug'
    | '/panel/accesos-invitados'
    | '/panel/administracion'
    | '/panel/captacion'
    | '/panel/clientes'
    | '/panel/dashboard'
    | '/panel/portal-cliente'
    | '/portal/candidatos'
    | '/portal/dossiers'
    | '/portal/solicitar'
    | '/auth/'
    | '/candidato/'
    | '/panel/'
    | '/portal/'
    | '/panel/candidatos/$id'
    | '/panel/candidatos/importar'
    | '/panel/proyectos/$id'
    | '/panel/candidatos/'
    | '/panel/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registro'
    | '/auth/callback'
    | '/c/$codigo'
    | '/casting/$slug'
    | '/dossier/$slug'
    | '/panel/accesos-invitados'
    | '/panel/administracion'
    | '/panel/captacion'
    | '/panel/clientes'
    | '/panel/dashboard'
    | '/panel/portal-cliente'
    | '/portal/candidatos'
    | '/portal/dossiers'
    | '/portal/solicitar'
    | '/auth'
    | '/candidato'
    | '/panel'
    | '/portal'
    | '/panel/candidatos/$id'
    | '/panel/candidatos/importar'
    | '/panel/proyectos/$id'
    | '/panel/candidatos'
    | '/panel/proyectos'
  id:
    | '__root__'
    | '/'
    | '/candidato'
    | '/panel'
    | '/portal'
    | '/registro'
    | '/auth/callback'
    | '/c/$codigo'
    | '/casting/$slug'
    | '/dossier/$slug'
    | '/panel/accesos-invitados'
    | '/panel/administracion'
    | '/panel/captacion'
    | '/panel/clientes'
    | '/panel/dashboard'
    | '/panel/portal-cliente'
    | '/portal/candidatos'
    | '/portal/dossiers'
    | '/portal/solicitar'
    | '/auth/'
    | '/candidato/'
    | '/panel/'
    | '/portal/'
    | '/panel/candidatos/$id'
    | '/panel/candidatos/importar'
    | '/panel/proyectos/$id'
    | '/panel/candidatos/'
    | '/panel/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatoRouteRoute: typeof CandidatoRouteRouteWithChildren
  PanelRouteRoute: typeof PanelRouteRouteWithChildren
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  RegistroRoute: typeof RegistroRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CCodigoRoute: typeof CCodigoRoute
  CastingSlugRoute: typeof CastingSlugRoute
  DossierSlugRoute: typeof DossierSlugRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$codigo': {
      id: '/c/$codigo'
      path: '/c/$codigo'
      fullPath: '/c/$codigo'
      preLoaderRoute: typeof CCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato/': {
      id: '/candidato/'
      path: '/'
      fullPath: '/candidato/'
      preLoaderRoute: typeof CandidatoIndexRouteImport
      parentRoute: typeof CandidatoRouteRoute
    }
    '/casting/$slug': {
      id: '/casting/$slug'
      path: '/casting/$slug'
      fullPath: '/casting/$slug'
      preLoaderRoute: typeof CastingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$slug': {
      id: '/dossier/$slug'
      path: '/dossier/$slug'
      fullPath: '/dossier/$slug'
      preLoaderRoute: typeof DossierSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/accesos-invitados': {
      id: '/panel/accesos-invitados'
      path: '/accesos-invitados'
      fullPath: '/panel/accesos-invitados'
      preLoaderRoute: typeof PanelAccesosInvitadosRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/administracion': {
      id: '/panel/administracion'
      path: '/administracion'
      fullPath: '/panel/administracion'
      preLoaderRoute: typeof PanelAdministracionRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/captacion': {
      id: '/panel/captacion'
      path: '/captacion'
      fullPath: '/panel/captacion'
      preLoaderRoute: typeof PanelCaptacionRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/clientes': {
      id: '/panel/clientes'
      path: '/clientes'
      fullPath: '/panel/clientes'
      preLoaderRoute: typeof PanelClientesRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/dashboard': {
      id: '/panel/dashboard'
      path: '/dashboard'
      fullPath: '/panel/dashboard'
      preLoaderRoute: typeof PanelDashboardRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/portal-cliente': {
      id: '/panel/portal-cliente'
      path: '/portal-cliente'
      fullPath: '/panel/portal-cliente'
      preLoaderRoute: typeof PanelPortalClienteRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/candidatos': {
      id: '/portal/candidatos'
      path: '/candidatos'
      fullPath: '/portal/candidatos'
      preLoaderRoute: typeof PortalCandidatosRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/dossiers': {
      id: '/portal/dossiers'
      path: '/dossiers'
      fullPath: '/portal/dossiers'
      preLoaderRoute: typeof PortalDossiersRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/solicitar': {
      id: '/portal/solicitar'
      path: '/solicitar'
      fullPath: '/portal/solicitar'
      preLoaderRoute: typeof PortalSolicitarRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/panel/candidatos/': {
      id: '/panel/candidatos/'
      path: '/candidatos'
      fullPath: '/panel/candidatos/'
      preLoaderRoute: typeof PanelCandidatosIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/candidatos/$id': {
      id: '/panel/candidatos/$id'
      path: '/candidatos/$id'
      fullPath: '/panel/candidatos/$id'
      preLoaderRoute: typeof PanelCandidatosIdRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/candidatos/importar': {
      id: '/panel/candidatos/importar'
      path: '/candidatos/importar'
      fullPath: '/panel/candidatos/importar'
      preLoaderRoute: typeof PanelCandidatosImportarRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/proyectos/': {
      id: '/panel/proyectos/'
      path: '/proyectos'
      fullPath: '/panel/proyectos/'
      preLoaderRoute: typeof PanelProyectosIndexRouteImport
      parentRoute: typeof PanelRouteRoute
    }
    '/panel/proyectos/$id': {
      id: '/panel/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/panel/proyectos/$id'
      preLoaderRoute: typeof PanelProyectosIdRouteImport
      parentRoute: typeof PanelRouteRoute
    }
  }
}

interface CandidatoRouteRouteChildren {
  CandidatoIndexRoute: typeof CandidatoIndexRoute
}

const CandidatoRouteRouteChildren: CandidatoRouteRouteChildren = {
  CandidatoIndexRoute: CandidatoIndexRoute,
}

const CandidatoRouteRouteWithChildren = CandidatoRouteRoute._addFileChildren(
  CandidatoRouteRouteChildren,
)

interface PanelRouteRouteChildren {
  PanelAccesosInvitadosRoute: typeof PanelAccesosInvitadosRoute
  PanelAdministracionRoute: typeof PanelAdministracionRoute
  PanelCaptacionRoute: typeof PanelCaptacionRoute
  PanelClientesRoute: typeof PanelClientesRoute
  PanelDashboardRoute: typeof PanelDashboardRoute
  PanelPortalClienteRoute: typeof PanelPortalClienteRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelCandidatosIdRoute: typeof PanelCandidatosIdRoute
  PanelCandidatosImportarRoute: typeof PanelCandidatosImportarRoute
  PanelProyectosIdRoute: typeof PanelProyectosIdRoute
  PanelCandidatosIndexRoute: typeof PanelCandidatosIndexRoute
  PanelProyectosIndexRoute: typeof PanelProyectosIndexRoute
}

const PanelRouteRouteChildren: PanelRouteRouteChildren = {
  PanelAccesosInvitadosRoute: PanelAccesosInvitadosRoute,
  PanelAdministracionRoute: PanelAdministracionRoute,
  PanelCaptacionRoute: PanelCaptacionRoute,
  PanelClientesRoute: PanelClientesRoute,
  PanelDashboardRoute: PanelDashboardRoute,
  PanelPortalClienteRoute: PanelPortalClienteRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelCandidatosIdRoute: PanelCandidatosIdRoute,
  PanelCandidatosImportarRoute: PanelCandidatosImportarRoute,
  PanelProyectosIdRoute: PanelProyectosIdRoute,
  PanelCandidatosIndexRoute: PanelCandidatosIndexRoute,
  PanelProyectosIndexRoute: PanelProyectosIndexRoute,
}

const PanelRouteRouteWithChildren = PanelRouteRoute._addFileChildren(
  PanelRouteRouteChildren,
)

interface PortalRouteRouteChildren {
  PortalCandidatosRoute: typeof PortalCandidatosRoute
  PortalDossiersRoute: typeof PortalDossiersRoute
  PortalSolicitarRoute: typeof PortalSolicitarRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalCandidatosRoute: PortalCandidatosRoute,
  PortalDossiersRoute: PortalDossiersRoute,
  PortalSolicitarRoute: PortalSolicitarRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatoRouteRoute: CandidatoRouteRouteWithChildren,
  PanelRouteRoute: PanelRouteRouteWithChildren,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  RegistroRoute: RegistroRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CCodigoRoute: CCodigoRoute,
  CastingSlugRoute: CastingSlugRoute,
  DossierSlugRoute: DossierSlugRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
