ALTER TABLE public.candidatos
  ADD COLUMN IF NOT EXISTS pasaporte text,
  ADD COLUMN IF NOT EXISTS numero_seguridad_social text,
  ADD COLUMN IF NOT EXISTS representacion text,
  ADD COLUMN IF NOT EXISTS nacionalidad text,
  ADD COLUMN IF NOT EXISTS nacionalidad_multiple text,
  ADD COLUMN IF NOT EXISTS lugar_nacimiento text,
  ADD COLUMN IF NOT EXISTS domicilio_fiscal_pais text,
  ADD COLUMN IF NOT EXISTS domicilio_fiscal_provincia text,
  ADD COLUMN IF NOT EXISTS domicilio_fiscal_localidad text,
  ADD COLUMN IF NOT EXISTS domicilio_fiscal_cp text,
  ADD COLUMN IF NOT EXISTS domicilio_fiscal_direccion text,
  ADD COLUMN IF NOT EXISTS telefono_2 text,
  ADD COLUMN IF NOT EXISTS email_2 text,
  ADD COLUMN IF NOT EXISTS web_url text,
  ADD COLUMN IF NOT EXISTS facebook_url text,
  ADD COLUMN IF NOT EXISTS twitter_url text,
  ADD COLUMN IF NOT EXISTS linkedin_url text,
  ADD COLUMN IF NOT EXISTS youtube_url text,
  ADD COLUMN IF NOT EXISTS twitch_url text,
  ADD COLUMN IF NOT EXISTS estudios jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS idiomas_detalle jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS acentos text,
  ADD COLUMN IF NOT EXISTS talla_chaqueta text,
  ADD COLUMN IF NOT EXISTS talla_zapato text,
  ADD COLUMN IF NOT EXISTS tipo_pelo text,
  ADD COLUMN IF NOT EXISTS complexion text,
  ADD COLUMN IF NOT EXISTS origen_etnia text,
  ADD COLUMN IF NOT EXISTS albino boolean,
  ADD COLUMN IF NOT EXISTS barbudo boolean,
  ADD COLUMN IF NOT EXISTS capacidad_diversa boolean,
  ADD COLUMN IF NOT EXISTS capacidad_diversa_tipo text,
  ADD COLUMN IF NOT EXISTS capacidad_diversa_obs text,
  ADD COLUMN IF NOT EXISTS habilidades jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS tipo_perfil jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS carnes_conducir jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS enlaces jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS otras_residencias jsonb DEFAULT '[]'::jsonb;