// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://eexciyzalqwejzyvqbsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleGNpeXphbHF3ZWp6eXZxYnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMjI0NDYsImV4cCI6MjEwNDU5ODQ0Nn0.0VA9jFWcVIx02Tk0FDoY6oPtNSuXEdMm57wfcrybJuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});